// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101160818_AddRefreshTokens")]
    partial class AddRefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            UserId = 3L
                        });
                });

            modelBuilder.Entity("backend.Models.CartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CartId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 9, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "iPhone 15 Pro Max",
                            Price = 1199.99m,
                            ProductType = 0,
                            ShortDescription = "Latest iPhone with Pro features and titanium design."
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 9, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 1099.99m,
                            ProductType = 0,
                            ShortDescription = "Premium Android phone with S Pen and incredible camera."
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 9, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "MacBook Pro 16\" M3",
                            Price = 2499.99m,
                            ProductType = 0,
                            ShortDescription = "Powerful laptop with M3 Max chip for professional work."
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 9, 1, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Dell XPS 13 Plus",
                            Price = 1299.99m,
                            ProductType = 0,
                            ShortDescription = "Ultra-portable Windows laptop with premium design."
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 9, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "iPad Pro 12.9\" M2",
                            Price = 1099.99m,
                            ProductType = 0,
                            ShortDescription = "Professional tablet with M2 chip and Apple Pencil support."
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 9, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Sony WH-1000XM5 Headphones",
                            Price = 349.99m,
                            ProductType = 0,
                            ShortDescription = "Industry-leading noise canceling wireless headphones."
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 9, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Apple Watch Series 9",
                            Price = 399.99m,
                            ProductType = 0,
                            ShortDescription = "Advanced health tracking and connectivity features."
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 9, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Nintendo Switch OLED",
                            Price = 349.99m,
                            ProductType = 0,
                            ShortDescription = "Portable gaming console with vibrant OLED screen."
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 9, 2, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "PlayStation 5",
                            Price = 499.99m,
                            ProductType = 0,
                            ShortDescription = "Next-gen gaming console with lightning-fast loading."
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 9, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Xbox Series X",
                            Price = 499.99m,
                            ProductType = 0,
                            ShortDescription = "Most powerful Xbox ever with 4K gaming."
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 9, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Canon EOS R5",
                            Price = 3899.99m,
                            ProductType = 0,
                            ShortDescription = "Professional mirrorless camera with 8K video recording."
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 9, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Sony A7 IV",
                            Price = 2498.99m,
                            ProductType = 0,
                            ShortDescription = "Full-frame mirrorless camera for content creators."
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 9, 2, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Samsung 65\" QLED 4K TV",
                            Price = 1299.99m,
                            ProductType = 0,
                            ShortDescription = "Premium smart TV with Quantum Dot technology."
                        },
                        new
                        {
                            Id = 14L,
                            CreatedAt = new DateTime(2025, 9, 2, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "LG OLED C3 55\"",
                            Price = 1799.99m,
                            ProductType = 0,
                            ShortDescription = "Perfect blacks and infinite contrast with OLED technology."
                        },
                        new
                        {
                            Id = 15L,
                            CreatedAt = new DateTime(2025, 9, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Bose SoundLink Revolve+",
                            Price = 299.99m,
                            ProductType = 0,
                            ShortDescription = "360-degree portable Bluetooth speaker."
                        },
                        new
                        {
                            Id = 16L,
                            CreatedAt = new DateTime(2025, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Apple AirPods Pro 2",
                            Price = 249.99m,
                            ProductType = 0,
                            ShortDescription = "Active noise cancellation with spatial audio."
                        },
                        new
                        {
                            Id = 17L,
                            CreatedAt = new DateTime(2025, 9, 3, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Samsung Galaxy Buds2 Pro",
                            Price = 199.99m,
                            ProductType = 0,
                            ShortDescription = "Premium wireless earbuds with intelligent ANC."
                        },
                        new
                        {
                            Id = 18L,
                            CreatedAt = new DateTime(2025, 9, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Microsoft Surface Pro 9",
                            Price = 1099.99m,
                            ProductType = 0,
                            ShortDescription = "Versatile 2-in-1 laptop and tablet hybrid."
                        },
                        new
                        {
                            Id = 19L,
                            CreatedAt = new DateTime(2025, 9, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Fitbit Sense 2",
                            Price = 299.99m,
                            ProductType = 0,
                            ShortDescription = "Advanced health and fitness smartwatch."
                        },
                        new
                        {
                            Id = 20L,
                            CreatedAt = new DateTime(2025, 9, 3, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Google Pixel 8 Pro",
                            Price = 999.99m,
                            ProductType = 0,
                            ShortDescription = "AI-powered camera with computational photography."
                        },
                        new
                        {
                            Id = 21L,
                            CreatedAt = new DateTime(2025, 9, 3, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Nike Air Max 270",
                            Price = 149.99m,
                            ProductType = 1,
                            ShortDescription = "Lifestyle sneakers with maximum Air cushioning."
                        },
                        new
                        {
                            Id = 22L,
                            CreatedAt = new DateTime(2025, 9, 3, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Adidas Ultraboost 23",
                            Price = 189.99m,
                            ProductType = 1,
                            ShortDescription = "Premium running shoes with responsive cushioning."
                        },
                        new
                        {
                            Id = 23L,
                            CreatedAt = new DateTime(2025, 9, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Levi's 511 Slim Jeans",
                            Price = 89.99m,
                            ProductType = 1,
                            ShortDescription = "Classic slim-fit jeans in premium stretch denim."
                        },
                        new
                        {
                            Id = 24L,
                            CreatedAt = new DateTime(2025, 9, 4, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Ralph Lauren Polo Shirt",
                            Price = 89.50m,
                            ProductType = 1,
                            ShortDescription = "Classic cotton polo with iconic pony logo."
                        },
                        new
                        {
                            Id = 25L,
                            CreatedAt = new DateTime(2025, 9, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Champion Reverse Weave Hoodie",
                            Price = 79.99m,
                            ProductType = 1,
                            ShortDescription = "Premium heavyweight hoodie with iconic logo."
                        },
                        new
                        {
                            Id = 26L,
                            CreatedAt = new DateTime(2025, 9, 4, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Patagonia Down Jacket",
                            Price = 229.99m,
                            ProductType = 1,
                            ShortDescription = "Lightweight insulation for outdoor adventures."
                        },
                        new
                        {
                            Id = 27L,
                            CreatedAt = new DateTime(2025, 9, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Uniqlo Heattech Long Sleeve",
                            Price = 19.90m,
                            ProductType = 1,
                            ShortDescription = "Ultra-warm base layer with moisture-wicking technology."
                        },
                        new
                        {
                            Id = 28L,
                            CreatedAt = new DateTime(2025, 9, 4, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Zara Wool Blend Coat",
                            Price = 199.99m,
                            ProductType = 1,
                            ShortDescription = "Elegant winter coat with tailored fit."
                        },
                        new
                        {
                            Id = 29L,
                            CreatedAt = new DateTime(2025, 9, 4, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Under Armour Athletic Shorts",
                            Price = 39.99m,
                            ProductType = 1,
                            ShortDescription = "Moisture-wicking shorts for intense workouts."
                        },
                        new
                        {
                            Id = 30L,
                            CreatedAt = new DateTime(2025, 9, 4, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Lululemon Align Leggings",
                            Price = 128.00m,
                            ProductType = 1,
                            ShortDescription = "Buttery-soft yoga leggings with four-way stretch."
                        },
                        new
                        {
                            Id = 31L,
                            CreatedAt = new DateTime(2025, 9, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "H&M Organic Cotton T-Shirt",
                            Price = 12.99m,
                            ProductType = 1,
                            ShortDescription = "Sustainable basic tee in soft organic cotton."
                        },
                        new
                        {
                            Id = 32L,
                            CreatedAt = new DateTime(2025, 9, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Calvin Klein Underwear Set",
                            Price = 49.99m,
                            ProductType = 1,
                            ShortDescription = "Premium cotton blend underwear for all-day comfort."
                        },
                        new
                        {
                            Id = 33L,
                            CreatedAt = new DateTime(2025, 9, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Converse Chuck Taylor All Star",
                            Price = 65.00m,
                            ProductType = 1,
                            ShortDescription = "Iconic canvas sneakers for casual style."
                        },
                        new
                        {
                            Id = 34L,
                            CreatedAt = new DateTime(2025, 9, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Tommy Hilfiger Button-Down Shirt",
                            Price = 79.99m,
                            ProductType = 1,
                            ShortDescription = "Classic dress shirt with signature flag logo."
                        },
                        new
                        {
                            Id = 35L,
                            CreatedAt = new DateTime(2025, 9, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Ray-Ban Aviator Sunglasses",
                            Price = 159.99m,
                            ProductType = 1,
                            ShortDescription = "Timeless aviator style with UV protection."
                        },
                        new
                        {
                            Id = 36L,
                            CreatedAt = new DateTime(2025, 9, 5, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Dyson V15 Detect Vacuum",
                            Price = 749.99m,
                            ProductType = 2,
                            ShortDescription = "Powerful cordless vacuum with laser detection."
                        },
                        new
                        {
                            Id = 37L,
                            CreatedAt = new DateTime(2025, 9, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "KitchenAid Stand Mixer",
                            Price = 449.99m,
                            ProductType = 2,
                            ShortDescription = "Professional-grade mixer for all your baking needs."
                        },
                        new
                        {
                            Id = 38L,
                            CreatedAt = new DateTime(2025, 9, 5, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Nespresso Vertuo Plus",
                            Price = 199.99m,
                            ProductType = 2,
                            ShortDescription = "Premium coffee machine with barista-quality results."
                        },
                        new
                        {
                            Id = 39L,
                            CreatedAt = new DateTime(2025, 9, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Instant Pot Duo 7-in-1",
                            Price = 99.99m,
                            ProductType = 2,
                            ShortDescription = "Multi-functional pressure cooker for quick meals."
                        },
                        new
                        {
                            Id = 40L,
                            CreatedAt = new DateTime(2025, 9, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Roomba i7+ Robot Vacuum",
                            Price = 799.99m,
                            ProductType = 2,
                            ShortDescription = "Smart vacuum that empties itself for weeks."
                        },
                        new
                        {
                            Id = 41L,
                            CreatedAt = new DateTime(2025, 9, 6, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Air Fryer Pro XL",
                            Price = 159.99m,
                            ProductType = 2,
                            ShortDescription = "Large capacity air fryer for healthy cooking."
                        },
                        new
                        {
                            Id = 42L,
                            CreatedAt = new DateTime(2025, 9, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Vitamix Professional Blender",
                            Price = 549.99m,
                            ProductType = 2,
                            ShortDescription = "High-performance blender for smoothies and more."
                        },
                        new
                        {
                            Id = 43L,
                            CreatedAt = new DateTime(2025, 9, 6, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Nest Learning Thermostat",
                            Price = 249.99m,
                            ProductType = 2,
                            ShortDescription = "Smart thermostat that learns your schedule."
                        },
                        new
                        {
                            Id = 44L,
                            CreatedAt = new DateTime(2025, 9, 6, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "The Psychology of Money",
                            Price = 24.99m,
                            ProductType = 3,
                            ShortDescription = "Timeless lessons on wealth, greed, and happiness."
                        },
                        new
                        {
                            Id = 45L,
                            CreatedAt = new DateTime(2025, 9, 6, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Atomic Habits",
                            Price = 18.99m,
                            ProductType = 3,
                            ShortDescription = "An easy and proven way to build good habits."
                        },
                        new
                        {
                            Id = 46L,
                            CreatedAt = new DateTime(2025, 9, 6, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Clean Code",
                            Price = 49.99m,
                            ProductType = 3,
                            ShortDescription = "A handbook of agile software craftsmanship."
                        },
                        new
                        {
                            Id = 47L,
                            CreatedAt = new DateTime(2025, 9, 6, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "The Midnight Library",
                            Price = 16.99m,
                            ProductType = 3,
                            ShortDescription = "A novel about all the choices that go into a life."
                        },
                        new
                        {
                            Id = 48L,
                            CreatedAt = new DateTime(2025, 9, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Sapiens: A Brief History",
                            Price = 22.99m,
                            ProductType = 3,
                            ShortDescription = "From animals into gods: a brief history of humankind."
                        },
                        new
                        {
                            Id = 49L,
                            CreatedAt = new DateTime(2025, 9, 7, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "The 7 Habits of Highly Effective People",
                            Price = 19.99m,
                            ProductType = 3,
                            ShortDescription = "Powerful lessons in personal change."
                        },
                        new
                        {
                            Id = 50L,
                            CreatedAt = new DateTime(2025, 9, 7, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "LEGO Creator Expert Set",
                            Price = 199.99m,
                            ProductType = 4,
                            ShortDescription = "Advanced building set for adult LEGO enthusiasts."
                        },
                        new
                        {
                            Id = 51L,
                            CreatedAt = new DateTime(2025, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Nintendo Switch Pro Controller",
                            Price = 69.99m,
                            ProductType = 4,
                            ShortDescription = "Premium gaming controller with enhanced precision."
                        },
                        new
                        {
                            Id = 52L,
                            CreatedAt = new DateTime(2025, 9, 7, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Rubik's Cube Speed Cube",
                            Price = 19.99m,
                            ProductType = 4,
                            ShortDescription = "Professional speed cube for competitive solving."
                        },
                        new
                        {
                            Id = 53L,
                            CreatedAt = new DateTime(2025, 9, 7, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Peloton Bike+",
                            Price = 2495.00m,
                            ProductType = 5,
                            ShortDescription = "Premium exercise bike with live and on-demand classes."
                        },
                        new
                        {
                            Id = 54L,
                            CreatedAt = new DateTime(2025, 9, 7, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Adjustable Dumbbell Set",
                            Price = 399.99m,
                            ProductType = 5,
                            ShortDescription = "Space-saving dumbbells that replace multiple weights."
                        },
                        new
                        {
                            Id = 55L,
                            CreatedAt = new DateTime(2025, 9, 7, 16, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Yoga Mat Premium",
                            Price = 89.99m,
                            ProductType = 5,
                            ShortDescription = "Non-slip yoga mat with superior cushioning."
                        },
                        new
                        {
                            Id = 56L,
                            CreatedAt = new DateTime(2025, 9, 8, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Dyson Airwrap Complete",
                            Price = 599.99m,
                            ProductType = 6,
                            ShortDescription = "Multi-styler for all hair types with no extreme heat."
                        },
                        new
                        {
                            Id = 57L,
                            CreatedAt = new DateTime(2025, 9, 8, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Skincare Routine Set",
                            Price = 149.99m,
                            ProductType = 6,
                            ShortDescription = "Complete skincare system for healthy, glowing skin."
                        },
                        new
                        {
                            Id = 58L,
                            CreatedAt = new DateTime(2025, 9, 8, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Herman Miller Aeron Chair",
                            Price = 1395.00m,
                            ProductType = 8,
                            ShortDescription = "Ergonomic office chair for all-day comfort."
                        },
                        new
                        {
                            Id = 59L,
                            CreatedAt = new DateTime(2025, 9, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Standing Desk Converter",
                            Price = 299.99m,
                            ProductType = 8,
                            ShortDescription = "Transform any desk into a healthy standing workspace."
                        },
                        new
                        {
                            Id = 60L,
                            CreatedAt = new DateTime(2025, 9, 8, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1L,
                            ImageUrl = "https://api.iconify.design/mdi:package-variant.svg?color=%23666666&width=400&height=400",
                            Name = "Tesla Model Y Accessories Kit",
                            Price = 499.99m,
                            ProductType = 9,
                            ShortDescription = "Premium accessories bundle for Tesla Model Y."
                        });
                });

            modelBuilder.Entity("backend.Models.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("int")
                        .HasAnnotation("MaxValue", 5)
                        .HasAnnotation("MinValue", 1);

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "admin@shop.com",
                            PasswordHash = "$2a$11$BbMMt.42L2iXd91aCm2qKOWLpjB1NaSCV6.jiK/SqCZoWZPwm2Jv.",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "john.doe@example.com",
                            PasswordHash = "$2a$11$Ii7loMC3ucGQYINIbAdU3./u1yIMwbvvr7CTwM/xxZ/8wZt.ri8/G",
                            Role = 0,
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = 3L,
                            Email = "jane.smith@example.com",
                            PasswordHash = "$2a$11$f5mO1DIdGORYG/s99NU3POFJzg/R0VwgrYauFU2ilz1AxiudHrJpu",
                            Role = 0,
                            Username = "jane_smith"
                        });
                });

            modelBuilder.Entity("backend.Models.Cart", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("backend.Models.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.CartItem", b =>
                {
                    b.HasOne("backend.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.HasOne("backend.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("backend.Models.RefreshToken", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.HasOne("backend.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("backend.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Cart");
                });
#pragma warning restore 612, 618
        }
    }
}
